apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-deployment
  labels:
    app: nginx
spec:
  replicas: {{ .Values.replica }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
      - name: img-pull-secret
      containers:
      - name: nginx
        image: {{ .Values.image }}
        ports:
        - containerPort: 80
