apiVersion: v1
kind: Service
metadata:
  name: sample-app-deployment
  labels:
    app: sample-app-deployment
spec:
  type: LoadBalancer
  selector:
    app: sample-app-deployment
  ports:
  - port: 80
    name: http
    targetPort: http
