name: Actions-Workflow

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.SP_TENANT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.SP_PASSWORD }}
  ARM_CLIENT_ID: ${{ secrets.SP_CLIENT_ID }}

on:
  push:
    branches:
      - tech-stack
    paths:
      - '.github/workflows/main.yaml'

jobs:
  terraform:
    name: terraform setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /home/runner/work/Demo_action/Demo_action/aks-cluster
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v1.4.0
        with:
          creds: '{ "clientId": "${{ secrets.SP_CLIENT_ID }}", "clientSecret": "${{ secrets.SP_PASSWORD }}", "subscriptionId": "${{ secrets.SUBSCRIPTION_ID }}", "tenantId": "${{ secrets.SP_TENANT_ID }}"}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        
      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Plan
        id: plan
        run: terraform plan
        
      - name: Terraform Apply
        run: terraform apply -auto-approve
        
        
