name: Actions-Workflow

on: push

jobs:
  test:
    name: test the work flow
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: build the maven project
        run: mvn -B package --file application/pom.xml

      - name: Unit test
        working-directory: application
        run: mvn -B verify

      - name: Upload Maven build artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact.jar
          path: application/target/AzureDevops-demo-1.0-SNAPSHOT.jar

      - uses: actions/checkout@v2
      - name: Download Maven build artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact.jar
          path: application/target
      - name: Build Docker container
        working-directory: application
        run: |
          docker build . -t shalinitest.azurecr.iot/javaimage:${{ github.sha }}
          docker push shalinitest.azurecr.io/javaimage:${{ github.sha }}
    