name: Actions-Workflow

on: push

jobs:
  test:
    name: test the work flow
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: build the maven project
        run: mvn -B package --file application/pom.xml

      - name: Unit test
        run: pwd
